"""Initial schema

Revision ID: 4eec9bcdad53
Revises: 
Create Date: 2026-04-07 15:34:40.893037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eec9bcdad53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subscription_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('counted_active', sa.Integer(), nullable=True),
    sa.Column('billed_active', sa.Integer(), nullable=True),
    sa.Column('usd_per_counted_slot', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('total_billed_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('owner_subsidy_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('fx_locked', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_date')
    )
    op.create_table('fx_rates',
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('usd_rub', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('rate_date')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('counted_in_denominator', sa.Boolean(), nullable=False),
    sa.Column('billable_after_cutover', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name')
    )
    op.create_table('legacy_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('opening_balance_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('rub_paid', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('fx_locked', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('usd_credit', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posted_charges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('charge_date', sa.Date(), nullable=False),
    sa.Column('counted', sa.Boolean(), nullable=False),
    sa.Column('billable', sa.Boolean(), nullable=False),
    sa.Column('active_count', sa.Integer(), nullable=False),
    sa.Column('subscription_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('charge_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('fx_locked', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('charge_rub_equivalent', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['charge_cycles.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'member_id', name='uq_charge_cycle_member')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posted_charges')
    op.drop_table('payments')
    op.drop_table('legacy_snapshot')
    op.drop_table('members')
    op.drop_table('fx_rates')
    op.drop_table('charge_cycles')
    # ### end Alembic commands ###
